### PR TITLE
Translation: Speed -> Pacing

### PR DESCRIPTION
**Pull request by jez9999**
As a result of this discussion: https://www.gamezworld.de/phpforum/viewtopic.php?pid=90441

... it seems like a better term for the movie Speed in English would be Pacing.

### CODE REVIEW

**Review by nittka — CHANGES_REQUESTED** [review]
Would you mind updating docs/manual_en.md accordingly? I could do it in a separate commit as well...

**Comment by jez9999** [comment]
Changed the manual wording, and a few other fixes too.

**Review by nittka — APPROVED** [review]

**Comment by nittka** [comment]
Thanks for proof reading and fixing the English manual as well. I'm fine with this change, but I'd like to have Ronny's OK, as well.

**Comment by GWRon** [comment]
I am fine with the pacing-change. But we should discuss (before merging) if we should change the variables/function internally too to "pacing".

I could care for savegame incompatibilities (renamed field handling).

**Comment by nittka** [comment]
I would not change anything but this translation. Refactoring the code is quite invasive and (in my opinion) unnecessary - it is not just field and method names but also the database...

**Pull request merged**
