### PR TITLE
Review of new ads' distribution

### PR DESCRIPTION
**Pull request by nittka**
I started going over the new ads. I changed the min audiences so that they are more evenly distributed over the existing slots. In particular the min audience value 12.5 had a lot more new entries than other slots.
In a second round, I will go over repetitions and duration. @scr0llbaer9000: maybe you could already check if any changes violate your intentions.

### CODE REVIEW

**Comment by scr0llbaer9000** [comment]
I'm mostly rather indifferent towards the ads parameters, and you mostly only did small relative changes it seems. (Just in general gameplay-wise I think almost all ads that require special target group should be more profitable to feel more rewarding to the player, they are hardly any different from those who require no such restrictions. In Mad TV this was very pronounced at times, but we don't have to do it in a that extreme way. Maybe we can go over this at a later point eventually.)

Only one small thing: "Anonymous" should only be one repetition.

The 'Macrohard' 'Enterprise' ads (`cc5f7107-f929-4331-8dcf-fc4dd2d7e606` and following) should probably should have the same parameters as the one in the `speedmininster.xml` file.

Also I forgot to move the ad entries that are not directly by me to the other files, will do that in a later PR.

**Comment by nittka** [comment]
* target group ads: they do get an automatic bonus roughly based on the target group's size (women/men less bonus than managers). However, it is a non-trivial problem (see https://github.com/TVTower/Documentation/blob/balancing/developer/concepts/wip_balancing/genre_targetgroups.md#zielgruppenwerbung);
* Macrohard: they should already have the same parameters; one reason why I changed them
* Anonymous: one repetition only for "Anonymous" or also for "Die Anonymen Anonymiker"? For that audience range, there were only ads with one or many repetitions: If you want all anonymous ads changed, I would also change Peureault to 2 ads in 4 days (1 in 7 seems strange anyway)

**Comment by scr0llbaer9000** [comment]
Yes all "Anonymous" / "Anonymiker". You can change "Peureault".

> Macrohard: they should already have the same parameters; one reason why I changed them

But you've made them different from `43e7451a-3eb1-4f91-9976-3e949c9ea8ed` now

**Comment by nittka** [comment]
* Peureault/Anonymous: changed
* 43e7451a-3eb1-4f91-9976-3e949c9ea8ed..., I haven't made them different - at least not that I am aware of. Please check on your side. Maybe it was a copy/paste error to begin with. Min audience and profit value of the original were not changed by your refactoring (ID was) and I changed the values of your versions accordingly.

**Comment by scr0llbaer9000** [comment]
I'm talking about these:

```
		<ad id="cc5f7107-f929-4331-8dcf-fc4dd2d7e606" comment="1980-1987 | https://en.wikipedia.org/wiki/Xenix">
			<title>
				<de>Xunix</de>
				<en>Xunix</en>
			</title>
			<description>
				<de>Besser als das Original! Das Betriebssystem von Macrohard speziell für Ihren Hochleistungsrechner.</de>
				<en>Better than the original! The operating system from Macrohard especially for your high-performance computer.</en>
			</description>
			<conditions min_audience="10.42" min_image="0" target_group="0" />
			<data infomercial="1" quality="15" repetitions="2" duration="3" profit="320" penalty="514" infomercial_profit="60" fix_infomercial_profit="1" />
			<availability year_range_from="1980" year_range_to="1987" />
		</ad>
		<ad id="cf636ccc-c253-45c5-afb8-c7aca1521f8b" comment="1988-1994 | https://en.wikipedia.org/wiki/LAN_Manager">
			<title>
				<de>LAN Master</de>
				<en>LAN Master</en>
			</title>
			<description>
				<de>Verbinden, Vereinen, Prosperieren. Die Lösung für Ihr Netzwerk von Macrohard.</de>
				<en>Connect, Combine, Prosper. The solution for your network by Macrohard.</en>
			</description>
			<conditions min_audience="10.42" min_image="0" target_group="0" />
			<data infomercial="1" quality="15" repetitions="2" duration="3" profit="320" penalty="514" infomercial_profit="60" fix_infomercial_profit="1" />
			<availability year_range_from="1988" year_range_to="1994" />
		</ad>
		<ad id="867c2c0b-69c4-4c90-be72-804e9fa939cb" comment="1995-2007 | https://en.wikipedia.org/wiki/MSN">
			<title>
				<de>MHN</de>
			</title>
			<description>
				<de>Das Portal und Ihr Pass für Ihre Reise in die digitalen Welten des Macrohard Netwebs.</de>
				<en>The portal and your passport for your journey into the digital worlds of the Macrohard Netweb.</en>
			</description>
			<conditions min_audience="10.42" min_image="0" target_group="0" />
			<data infomercial="1" quality="15" repetitions="2" duration="3" profit="320" penalty="514" infomercial_profit="60" fix_infomercial_profit="1" />
			<availability year_range_from="1995" year_range_to="2007" />
		</ad>

```
They are now different from the one in `speedminister.xml` which I don't see you updated:

```
		<ad id="43e7451a-3eb1-4f91-9976-3e949c9ea8ed" creator="8605" created_by="SpeedMinister" comment="2008- | https://en.wikipedia.org/wiki/Microsoft_Azure | previous id: speedminister-ad-Mikrohard">
			<title>
				<de>Macrohard Arctic - Die Software Klaut</de>
				<en>Macrohard Arctic - The Software Clout</en>
				<pl>Macrohard Software Fraud</pl>
			</title>
			<description>
				<de>Kaufen(!) Sie unsere Software und laden Sie Ihre Firmengeheimnisse SELBST auf unsere Server. Da bleibt es dann unter 5 Augen! Danke.</de>
				<en>Buy(!) our software and upload your company secrets YOURSELF on our servers. Then things can remain confidential under 5 eyes! Thank you.</en>
				<pl>Kup(!) nasze oprogramowanie i prześlij swoje tajemnice firmowe na nasze serwery. Wtedy wszystko może pozostać poufne! Dziękujemy.</pl>
			</description>
			<conditions min_audience="10.42" min_image="0" target_group="0" />
			<data infomercial="1" quality="15" repetitions="1" duration="2" profit="320" penalty="514" infomercial_profit="60" fix_infomercial_profit="1" />
			<availability year_range_from="2008" /> <!-- different years variations added in constr -->
		</ad>
```

**Comment by nittka** [comment]
OK. I was grouping the wrong ads.
I changed the number of spots of the new group from 1/2 to 3/2. Otherwise there would have been to many 1 spot ads for that min audience for my taste.

**Comment by scr0llbaer9000** [comment]
yeah that's fine

**Pull request merged**
