### PR TITLE
Zielgruppendefinition Drehbuchvorlagen; Report scr0llbaer

### LINKED ISSUE #1152: Is target_groups_optional even evaluated?
The docu says the XML attribute `target_groups_optional` means "möglicherweise verwendete [Zielgruppe](https://github.com/TVTower/Documentation/blob/master/database_de/main.md#Zielgruppe)". It's not really clear what that means, but I *think* I read somewhere else that it's supposed to be just an additional, albeit weaker form of the `target_groups`. Though when looking at the code, it seems it is ignored entirely?

		'=== GROUPS ===
		Local nodeGroups:TxmlNode = xml.FindChildLC(node, "groups")
		data.Clear()
		If Not _programmeLicenceDataGroupsKeys
			_programmeLicenceDataGroupsKeys = [..
				"target_groups", "pro_pressure_groups", "contra_pressure_groups" ..
			]
		EndIf
		xml.LoadValuesToDataCSK(nodeGroups, data, _programmeLicenceDataGroupsKeys)
		programmeData.targetGroups = data.GetInt("target_groups", programmeData.targetGroups)
		programmeData.proPressureGroups = data.GetInt("pro_pressure_groups", programmeData.proPressureGroups)
		programmeData.contraPressureGroups = data.GetInt("contra_pressure_groups", programmeData.contraPressureGroups)

Also, given that it is implemented, it isn't really clear how to use this. To maximally boost a certain audience, can it be specified in both parameters, `target_groups` *and* `target_groups_optional`? Or should it be handled more like either-or?

### PR DESCRIPTION
**Pull request by nittka**
closes #1152

### CODE REVIEW

**Comment by scr0llbaer9000** [comment]
When we're "refactoring" the XML data anyway wouldn't it make sense to make programmes and scripts consistent? At one place the target groups are part of the `data` tag, at the other they aren't.

**Comment by nittka** [comment]
Yes, that's the other option. However, I would not allow target_groups_optional for programmes, only for script templates.

**Comment by nittka** [comment]
@GWRon : before I make another refactoring, I'd like to have your opinion. Unifying the group syntax for programmes and script templates would be fine with me. (Programmes do not support optional target groups, script templates do not support pressure groups at the moment.)

**Comment by scr0llbaer9000** [comment]
> However, I would not allow target_groups_optional for programmes, only for script templates.

That is fine and is consistent with the other attributes that have the `_optional` option for screenplays.

> Unifying the group syntax for programmes and script templates would be fine with me.

Actually it doesn't necessarily need to be unified, but the weird thing right now is that with this attribute it's completely the other way round. For example for `programme` we have `blocks`, `genre`(s), `outcome` etc as attributes in the `data` tag, for scripts their they are tags. The reason is because they support more options for variety (`min` and `max` for blocks etc). So it's rather with programmes that the `target_groups` could be included in the `data` tag, while for scripts `groups` could be their own tag to offer more options to allow for variations.

(For artistic / creative reasons, I find the `target_groups_optional` not very usable though, because in most cases you would not want some of the target groups to be determined completely randomly, but rather bind them to certain variations. E.g. "Patty Glansen invites Archie Arbeitslos (unemployed) | Elon Musk (managers)".)

**Comment by GWRon** [comment]
I thought I have had written a reply to here (regarding @scr0llbaer9000 's remarks). 

Anyways... maybe I just dreamed doing it so I try to repeat myself now:
Regarding "conditions" or "variations" I thought we could defer that to some "scripts" section we could add. I mean, something we could run after "creation" of an object and which could manipulate things to your needs and which is based on the new script expression "engine" (of course we could also consider "lua" there...).
```
<data ... />
<modscripts>
  <modscript type="post_creation">${.if:.scriptGenreID:1:${.scriptSetCast:1:"id-von-elon"}}</modscript>
  <modscript type="post_creation">${.if:.scriptCastContains:"id-von-archie":${.scriptSetCast:1:"id-von-elon"}}</modscript>
...
</modscripts>
```
also Hilfsmittlel, mit denen man dieses gewuenschte Verhalten ermoeglicht. Allerdings werden sich "komplexe" Dinge eher mit Lua realisieren lassen - und dann faehrt man schnell zweigleisig (ScriptExpression vs Lua). Bei haeufig ausgefuehrten Dingen sind die ScriptExpressions evtl schneller/leichtgewichtiger - Drehbuecher etc werden aber evtl selten genug kreiiert um Lua ins Auge zu nehmen.

(Generell koennte eine Luainstanz vorgehalten werden, die mit den richtigen Skripten gefuettert voellig ausreichend waere).

**Review by GWRon — APPROVED** [review]

**Comment by nittka** [comment]
@scr0llbaer9000: how about the following approach. We apply the changes of this PR as is, adding the target_group attributes into data. If target_groups_optional is seldom used, it is no loss.
Once there is a real need to have a more complicated configuration for the groups, we can introduce a script template specific group-tag syntax.

**Comment by scr0llbaer9000** [comment]
I would really prefer the `target_groups` for scripts not be in `data` because it was never documented that way and is unnecessarily inconsistent, but if it's too much effort to change that then I guess we have to go along with it.

**Comment by nittka** [comment]
I am not perfectly happy, either. But right now, it is a valid solution.
The documentation was wrong from the start. Basis for the documentation was not the database processing code (database.bmx) but the actual database files at the time. I assume that for script template groups the code and the actual database never matched and nobody noticed...

I propose to use this change for now, because it is unclear how things will develop, once there is a real need to do a more fine grained randomization/configuration of target groups and pressure groups for script templates. If this happens, we may not want to have one groups tag but rather one for target groups, one for pro and one for contra pressure groups.

I will leave this PR open and wait for the translation PR to be merged, as there will be merge conflicts which I will resolve (rather than pauldim).

**Comment by nittka** [comment]
Update of the documentation and a new editor version will follow shortly.

**Pull request merged**
