### PR TITLE
Add missing English translations, revise existing ones in res/Databas…

### PR DESCRIPTION
**Pull request by scr0llbaer**
**Add missing English translations, revise existing ones in res/Database and res/Lang, add missing IMDB data, separate out fictional data, add new data.**

This is a massive update, and I hope you guys can take the time to review and merge it.

----

(1)

I have added all missing English translations, in the `database/Default` directory as well as in the `database/Default/user` directory.

----

(2)

The already existing translations to English seemed by and large a rush-job or afterthought (a lot of 'denglish', typos, grammar and spelling mistakes), hence I have revised them thoroughly.

An English version of the game should now be in a 'presentable' state, but there's still room for improvements that someone with a more fluid and fresh writing style is welcomed to apply.

I took liberties to add or 'save' puns where I could, or improve on the existing ones.

----

(3)

I have applied some corrections and improvements to the English resource files in `res/lang` as well.
For example, "Topicality" is not a very intuitively understandable word. "Recency" is often used in such context, but why not "Freshness".

----

(4)

Some of the existing mistakes were in context of variables and templating. I have diligently worked through everything, it was by no means a rushed job.

----

(5)

Generally, through all this process I also found and corrected some mistakes in the original German.

----

(6)

I have added all missing IMDB references in the people and programme data, and I also found some erroneous data that I corrected.

----

(7)

I found some duplicates in the people data that I carefully 'merged', checking all references.

----

(8)

I added birthday and deathday data where it was missing, also to the 'insignificant' people, if the information was available on IMDB or Wikipedia. This data could be used to trigger news events in the game.

----

(9)

I added all missing original person names and movie titles, and also found some erroneous ones that I corrected. It should now be very easy for new contributors to search for existing data, which should avoid duplicates in the future.

----

(10)

The fictional movies and fictional people in the files in the main directory I have separated out line by line into separate files, `database_people_fictional.xml` and `database_programmes_fictional.xml` respectively.

Along with the complete IMDB data that is now consistently and reliably present, this now makes the necessary search and replace operations to play with 'real' data trivial even for end-users that are less technically sophisticated.

----

(11)

In the `database_programmes.xml` file I furthermore have replaced actors and people that were spelled out in clear text in the descriptions with references.

----

(12)

I have added dozens of movies and series, along with the personnel.

----

(13)

These contain an implicit proposal how data contributors could deal with series like Baywatch or X-Files. Basically keep the seasons but reduce the number of episodes to 1/4th or 1/5th, selecting only some representative episodes. And probably most won't bother to add much more than the first 2 seasons anyway.

----

(14)

I added items of other categories as well, now in my own user file `scr0llbaer.xml`, first and foremost a couple of scripts for shows, movies and series.

----

(15)

Some of those are "endless" formats, i.e. shows that can be produced anew every day, like the typical breakfast TV. To achieve that I just specified a very high (symbolic) number for `production_limit`. I don't know if this could cause any technical problems, or if the "endless" format is desired at all from a game balancing perspective?

----

(16)

I'm aware these are massive changes that you guys probably won't accept so lightly, but everything "works on my machine" (TM) just fine, I have tested pretty thoroughly, both in German and in English, both with the standard-fake and with the original-real data. I have a good overview and grasp on the available data set now, and could play the role as a "inventory data janitor" for this project if so desired.

----

Glad to discuss everything down to a case-by-case basis. :)

Concerning my own data I don't care so much about values and parameters, so others are free to adjust them. I just want to see more content in the game. I'm planning to continue to add content to my local repository every day, and correct things that I happen to run over.

### CODE REVIEW

**Comment by nittka** [comment]
Thanks for the massive work!!! It will take some time to do the review. It would have been more convenient (for me) to split up the work. In particular fixing entries and separating them into different files is hard to review because the diff cannot show corresponding entries next to each other. So it is not obvious which changes were actually made.

Maybe you could still split up this pull request into three different ones
* review of the existing database
* new own database entries
* review of localization (res/lang) - I cannot make you, but as it seems an important topic to you, could you also glance over the manual (docs/manual.md). At least some terminology should be adapted to the changes you made to the English translation.

This would simplify the review and merge process.

**Comment by GWRon** [comment]
Sehr schoen - Account scheint wieder aktiviert zu sein.

**Comment by nittka** [comment]
This PR has re-appeared. Should we close it and continue the work in the other(s)?

**Comment by scr0llbaer** [comment]
oh wow, account is back, maybe for good.

yes, handled in https://github.com/TVTower/TVTower/pull/884#

closing

**Pull request closed without merging**
