### PR TITLE
Redoing all changes of res-update-1 in 1 commit

### PR DESCRIPTION
**Pull request by scr0llbaer9000**
As discussed in https://github.com/TVTower/TVTower/pull/884#

### CODE REVIEW

**Comment by nittka** [comment]
I have checked that the changes of this PR are exactly the ones from #884. (Local rebase of that branch, comparison of the resulting states).
As discussed in the original PR, all issues found while reviewing have been adressed.

**Comment by nittka** [comment]
I suggest, you delete the now obsolete branches in your fork and start with a new one from master.

**Comment by GWRon** [comment]
@nittka
A different merge-commit-title would have been better

**Comment by nittka** [comment]
I know. I used rebase and merge (no option to edit the title), maybe squash and merge would have been better (can you edit the title then?).
But I am reluctant to modify the master at this point...

**Comment by scr0llbaer9000** [comment]
sorry about that, I really did expect it would get a new commit title anyway somehow.

**Pull request merged**
