### PR TITLE
Review Fokus-Punkte and Personenattribute

### PR DESCRIPTION
**Pull request by nittka**
Ich bin mal die Liste der Genre durchgegangen und habe Modifikatoren ergänzt,

### CODE REVIEW

**Comment by scr0llbaer9000** [comment]
Just my intuitions, but I don't wanna bikeshed too much:

**Adventure:**

> `<outfit_and_mask value="1.2" />`

Maybe a bit too high, less important here, heroes mostly wear everyday clothes etc...

**Animation:**

> `<vfx_and_sfx value="1.2" />`

Could be maxed out as the only important parameter, and the others could be lowered to their minimum.

**Erotic:**

> `<outfit_and_mask value="0.8" />`

Isn't that a mistake? Sure, they're mostly naked `;)` ... BUT ... Maybe some fetish gear is sometimes used, and comparing how erotic stars look in with make-up vs in real life... guess the parameter should at least be neutral.

**Family:**

Probably coulisse should be 1.1 or 1.2.
They're mostly about the "heile Welt" and the interiors and props shouldn't look shabby and cheap.

**Fantasy:**

> `<stunts value="0.8" />`

Disagreeing with that, at least it should be neutral to be determined by the secondary genres.
Fantasy can be action-oriented like "Conan the Barbarian" or family-oriented like "The NeverEnding Story" (though even that has a fair amount of stunt action afair) or "The Wizard of Oz".
Are secondary genres already considered here? 

**Monumental:**

> `<stunts value="0.5" />`
> `<vfx_and_sfx value="0.9" />`

Disagreeing with that, e.g. "Ben Hur" which is full of these things.
At least should be neutral.
Epic movies are trying to max out in every aspect. https://tvtropes.org/pmwiki/pmwiki.php/Main/EpicMovie
(Of course begging the question if a small studio producing an epic makes any sense at all. Maybe indeed all parameters should be maxed up so it *will* be difficult and expensive to achieve a good outcome.)

**SciFi:**

> `<stunts value="1.2" />`

I think that can be removed, not much stunt action in "2001: A Space Odyssey" - should be left to secondary genres.

**Thriller:**

> `<stunts value="0.8" />`

dito. Psycho-thriller or action-thriller?

**Feature:**

> `<vfx_and_sfx value="0.5" />`

Feature is often used together with documentary where this value is over 1, so it probably shouldn't draw that aspect down that much.

----

Also just noticing the "supporting actors" settings.
They're set too strong in my opinion.
Supporting actors, for me anyway, are often like the grandma of the hero in an action movie. No need for her also to have "power" or good looks. At least that's how I always interpreted and understood it as a player.

**Comment by GWRon** [comment]
Ignoring changes but stating my opinion about the "modifiers" in general.

If movie genres have subgenres, then we could of course somehow calculate the modifiers based on them.
So an fantasy-action movie will have more weight put on stunts, if it is scifi, then more vfx ...).
A scifi-drama would possibly have high vfx because of scifi and less high one because of drama...

And yes, for all combinations there are exceptions. So visually pleasant scifi dramas and action heavy fantasy stuff full of stunts and but not requiring any "high level" make up because of no goblins or orcs running around, an no wounds o be seen etc (so PG-rated action).

Yet we always have to think cliche ... because "cliche" means it will fit to the majority of the movies (of that genre(-mix)).
There is fetish erotic and ... the one of the "sports clip era". Some want to be more "movie like" (rare) others simply stare some nudity even disregarding facial makeup.

Dunno if we need to distinguish between eg an pure "erotic movie" (just there to show some bare breasts) and eg an "erotic thriller" (basic instinct) which already by its "genre mix" exposes that it wants to be a bit "more" and thus most probably also paid attention to mask, scene props, ...


Anyways ... for fictional stuff I always would prefer "cliche thinking" as this will make it easier for people to "do estimations". Scifi -> VFX, Music show -> coulisse and fx (show effects), Lovestories -> Makeup and Coulisse (should just look "good") etc.

**Comment by nittka** [comment]
I have adapted some of the values. If I interpret TMovieGenreDefinitionCollection#createAggregatedMovieGenreDefinition correctly focus points are already combined for multiple genres.
I have not really dived into the code calculating the outcome of a production and balancing those is a major issue. With respect to supporting actors the argument would be (if correctly implemented): director and main actors are most important for a production, but if supporting actors are required it should actually matter who is chosen which is why I think high attribute values are OK.

**Comment by nittka** [comment]
@scr0llbaer9000 : Could you check the changes I made wrt. your comments (second commit). The idea was to create a new base line for further changes, where more relevant attributes are already present for the genres.

**Comment by scr0llbaer9000** [comment]
fine by me, give or take 0.1 here and there won't matter much I suppose `;)`

**Pull request merged**
