### PR TITLE
Separation of fictional entries

### PR DESCRIPTION
**Pull request by scr0llbaer9000**
Now on to the second part of my update to the `res` files.

Fictional movies/programmes and fictional persons in the files in the main `database/Default` directory I have separated out line by line into separate files, `database_people_fictional.xml` and `database_programmes_fictional.xml` respectively.

Along with the complete IMDB data that is now consistently and reliably present in the `_original` XML tags, this now makes the necessary search and replace operations to play with 'real' data trivial even for end-users that are less technically sophisticated.

It also feels cleaner to have the data separated this way. To have all fictional entries in one file may inspire to work on the "story line" or the "parallel universe" that this game offers.

No other changes were made to the data in this commit.

I have also compared this branch with the version of my data from a few weeks back, and I came to the same result, so from my side everything is fine, it all is in the right place.

I don't know of any good diff tools that allow easy verification of this sort of change.

### CODE REVIEW

**Comment by scr0llbaer9000** [comment]
some whitespace indentation (spaces to tabs) was also "fixed" in the process though, I hope that's not a problem.

**Comment by nittka** [comment]
Some comments for the first commit. (With the second, I have to do the checks once more and give feedback later).
As I said, reordering entries is hard to review because the normal diff tools fail. What I did was a very low-tech normalization of the files (with no guarantee that I did not miss anything relevant) - read all entries from multiple files, sort them by ID, serializing them into one file.
Doing this for the original database files and the refactored ones, the resulting normalized files should be identical. For the first commit this is the case.

However, I noticed that not all programs are labelled correctly
* TheRob-serie-WunderderMeere-Ep002 marked fictional but in regular programmes file
* TheRob-serie-Sanddornkahn marked fictional
* A number of user programmes are not marked as fictional.

My proposal would be to do the reordering (no attribute changes) in one PR. The potential attribute fixes should be a separate one.

**Comment by scr0llbaer9000** [comment]
> (With the second, I have to do the checks once more and give feedback later)

Sorry for race condition. `:)`

> My proposal would be to do the reordering (no attribute changes) in one PR. The potential attribute fixes should be a separate one.

yes, I noticed these too. And also was planning to fix that in separate PR.
Though for the user files I had thought one can assume everything should be fictional anyway, but either way it's better to mark them explicitly.

Generally, there's also the problem, and there are several cases already, that a series can be non-fictional, but the individual episodes are freely made up, hence, technically, fictional. I *guess* it's correct that the episodes should be labeled as fictional then. I so far made sure they had `_original` tags (often redundantly), but maybe it's also possible (and cleaner) to move only the episodes to the fictional file (@GWRon explained that data with same ID "merges", so this would be applicable here).

**Comment by nittka** [comment]
@GWRon: I checked the current state once mode. As far as I can see, the data is identical to the state before as intended. Could be merged.

With respect to a non-fictional series with fictional episodes, my suggestion would be not to separate the entries. Place them in programmes.xml and mark the episode as fictional with duplicate titles. I would find that much less confusing than having episodes without a parent in a totally different file. Also, I would not really know how the separation should be done. In order for the episode to belong to the series' main entry, it has to be a child node, so programmes (non-fictional) would have to have a corresponding child entry anyway... Just keep them in one place.

**Review by nittka — APPROVED** [review]

**Comment by GWRon** [comment]
Ok, then merge please if there's nothing more to come in this PR.

**Pull request merged**
